# Generated by Django 4.2.3 on 2023-08-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=100)),
                ('transcript_id', models.CharField(max_length=100)),
                ('numbers', models.IntegerField()),
            ],
        ),
    ]
